import bcrypt from "bcryptjs";
import type { Brand } from "@/lib/types";
import type { Coupon, DemoUser, StoredProduct } from "./types";

export function seedUsers(): DemoUser[] {
  return [
    {
      id: "demo-user-1",
      name: "Cliente Demo",
      email: "demo@fluxoflx.com",
      passwordHash: bcrypt.hashSync("fluxo1234", 10),
      role: "customer",
      addresses: [
        {
          id: "addr-1",
          label: "Casa",
          recipient: "Cliente Demo",
          cpf: "529.982.247-25",
          street: "Rua das Dunas",
          number: "120",
          neighborhood: "Ponta Negra",
          city: "Natal",
          state: "RN",
          zip: "59090-000",
        },
      ],
    },
    {
      id: "demo-admin-1",
      name: "Admin Demo",
      email: "admin@fluxoflx.com",
      passwordHash: bcrypt.hashSync("fluxo1234", 10),
      role: "admin",
      addresses: [],
    },
  ];
}

export function seedCoupons(): Coupon[] {
  return [
    { code: "FLUXO10", type: "percentual", value: 10, usageCount: 0, active: true },
    { code: "BEMVINDO20", type: "fixo", value: 20, minSubtotal: 100, usageCount: 0, active: true },
    { code: "FRETEGRATIS", type: "frete-gratis", value: 0, usageCount: 0, active: true },
  ];
}

/**
 * All brands and products below are DEMO content for development only.
 * Fluxo FLX is a multibrand curation — no products are attributed to
 * real brands without data supplied by that brand.
 */
export function seedBrands(): Brand[] {
  return [
    {
      slug: "marca-demo-01",
      name: "Marca Demo 01",
      tagline: "Performance para quem não para.",
      description:
        "Performance, autenticidade e estilo para quem vive em movimento. Peças técnicas pensadas para o treino e para o dia.",
      history:
        "DEMO: história da marca a ser substituída por conteúdo real fornecido pela marca parceira.",
      categories: ["fitness"],
      accent: "petrol",
    },
    {
      slug: "marca-demo-02",
      name: "Marca Demo 02",
      tagline: "Liberdade em cada onda.",
      description:
        "Surfwear com identidade de praia e cultura litorânea, para quem vive o mar e carrega esse ritmo para a cidade.",
      history:
        "DEMO: história da marca a ser substituída por conteúdo real fornecido pela marca parceira.",
      categories: ["surf"],
      accent: "sand",
    },
    {
      slug: "marca-demo-03",
      name: "Marca Demo 03",
      tagline: "Essenciais para o seu dia.",
      description:
        "Peças casuais de corte contemporâneo, o básico bem resolvido para transitar do trabalho ao fim de semana.",
      history:
        "DEMO: história da marca a ser substituída por conteúdo real fornecido pela marca parceira.",
      categories: ["casual"],
      accent: "ink",
    },
    {
      slug: "marca-demo-04",
      name: "Marca Demo 04",
      tagline: "Do treino à rua, sem pausas.",
      description:
        "Uma curadoria híbrida entre performance e streetwear, para quem não separa o treino do estilo de vida.",
      history:
        "DEMO: história da marca a ser substituída por conteúdo real fornecido pela marca parceira.",
      categories: ["fitness", "casual"],
      accent: "petrol",
    },
  ];
}

const sizesApparel = ["PP", "P", "M", "G", "GG"];
const sizesAccessory = ["Único"];

const camisetaSizeGuide = [
  { label: "Comprimento", values: { PP: "68", P: "71", M: "73", G: "74", GG: "75" } },
  { label: "Tórax", values: { PP: "48", P: "51", M: "54", G: "56", GG: "58" } },
  { label: "Barra", values: { PP: "48", P: "51", M: "54", G: "56", GG: "58" } },
  { label: "Alt. manga", values: { PP: "32,5", P: "33,5", M: "34,5", G: "35", GG: "36" } },
];
const shortsSizeGuide = [
  { label: "Cintura", values: { PP: "70", P: "74", M: "78", G: "82", GG: "86" } },
  { label: "Quadril", values: { PP: "88", P: "92", M: "96", G: "100", GG: "104" } },
  { label: "Comprimento", values: { PP: "42", P: "44", M: "46", G: "48", GG: "50" } },
];
const calcaSizeGuide = [
  { label: "Cintura", values: { PP: "70", P: "74", M: "78", G: "82", GG: "86" } },
  { label: "Quadril", values: { PP: "90", P: "94", M: "98", G: "102", GG: "106" } },
  { label: "Comprimento", values: { PP: "98", P: "100", M: "102", G: "104", GG: "106" } },
];
const boneSizeGuide = [{ label: "Circunferência", values: { Único: "56 a 60 (ajustável)" } }];

export function seedProducts(): StoredProduct[] {
  return [
    {
      sizeGuideRows: camisetaSizeGuide,
      slug: "camiseta-performance-dry",
      name: "Camiseta Performance Dry",
      brandSlug: "marca-demo-01",
      category: "fitness",
      subcategory: "Camisetas",
      price: 149.9,
      stock: 18,
      colors: [
        { name: "Preto", hex: "#111111" },
        { name: "Grafite", hex: "#666666" },
      ],
      sizes: sizesApparel,
      description:
        "Camiseta técnica de secagem rápida, com tecido leve e respirável para treinos de alta intensidade.",
      composition: "88% poliamida, 12% elastano.",
      care: ["Lavar à máquina em água fria", "Não usar alvejante", "Secar à sombra"],
      isNew: true,
      tags: ["treino", "dry-fit", "academia"],
      relatedSlugs: ["shorts-training-flex", "bone-performance"],
    },
    {
      sizeGuideRows: camisetaSizeGuide,
      slug: "regata-treino-fluxo",
      name: "Regata Treino Fluxo",
      brandSlug: "marca-demo-01",
      category: "fitness",
      subcategory: "Regatas",
      price: 119.9,
      stock: 24,
      colors: [{ name: "Preto", hex: "#111111" }],
      sizes: sizesApparel,
      description: "Regata de corte solto com abertura lateral para máxima liberdade de movimento.",
      composition: "95% poliéster, 5% elastano.",
      care: ["Lavar à máquina em água fria", "Não passar ferro sobre estampa"],
      isBestSeller: true,
      tags: ["treino", "academia"],
      relatedSlugs: ["shorts-training-flex", "camiseta-performance-dry"],
    },
    {
      sizeGuideRows: shortsSizeGuide,
      slug: "shorts-training-flex",
      name: "Shorts Training Flex",
      brandSlug: "marca-demo-01",
      category: "fitness",
      subcategory: "Shorts",
      price: 169.9,
      compareAtPrice: 199.9,
      stock: 3,
      colors: [
        { name: "Preto", hex: "#111111" },
        { name: "Cinza", hex: "#6b6b6b" },
      ],
      sizes: sizesApparel,
      description: "Shorts com forro interno e tecido com quatro direções de elasticidade.",
      composition: "90% poliamida, 10% elastano.",
      care: ["Lavar à máquina em água fria", "Não usar secadora"],
      isBestSeller: true,
      tags: ["treino", "corrida"],
      relatedSlugs: ["camiseta-performance-dry", "bone-performance"],
    },
    {
      sizeGuideRows: boneSizeGuide,
      slug: "bone-performance",
      name: "Boné Performance",
      brandSlug: "marca-demo-01",
      category: "fitness",
      subcategory: "Acessórios",
      price: 89.9,
      stock: 40,
      colors: [{ name: "Preto", hex: "#111111" }],
      sizes: sizesAccessory,
      description: "Boné leve com aba curva e ajuste traseiro, ideal para treino ao ar livre.",
      composition: "100% poliéster.",
      care: ["Limpar com pano úmido", "Não lavar à máquina"],
      tags: ["acessório", "corrida"],
    },
    {
      sizeGuideRows: shortsSizeGuide,
      slug: "boardshort-fluxo-wave",
      name: "Boardshort Fluxo Wave",
      brandSlug: "marca-demo-02",
      category: "surf",
      subcategory: "Boardshorts",
      price: 179.9,
      stock: 12,
      colors: [
        { name: "Areia", hex: "#d8cbb7" },
        { name: "Petróleo", hex: "#0f5b5b" },
      ],
      sizes: sizesApparel,
      description: "Boardshort de secagem rápida com cintura elástica e bolso interno com zíper.",
      composition: "100% poliéster reciclado.",
      care: ["Lavar à mão", "Não torcer", "Secar à sombra"],
      isNew: true,
      tags: ["surf", "praia"],
      relatedSlugs: ["camiseta-tide-surf", "bone-surf-classic"],
    },
    {
      sizeGuideRows: camisetaSizeGuide,
      slug: "camiseta-tide-surf",
      name: "Camiseta Tide Surf",
      brandSlug: "marca-demo-02",
      category: "surf",
      subcategory: "Camisetas",
      price: 129.9,
      stock: 0,
      colors: [
        { name: "Areia", hex: "#d8cbb7" },
        { name: "Branco", hex: "#f5f5f5" },
      ],
      sizes: sizesApparel,
      description: "Camiseta 100% algodão com estampa inspirada em ondas e movimento.",
      composition: "100% algodão penteado.",
      care: ["Lavar à máquina em água fria", "Virar do lado de dentro antes de lavar"],
      isBestSeller: true,
      tags: ["surf", "praia", "casual"],
      relatedSlugs: ["boardshort-fluxo-wave", "bone-surf-classic"],
    },
    {
      sizeGuideRows: camisetaSizeGuide,
      slug: "regata-costa-livre",
      name: "Regata Costa Livre",
      brandSlug: "marca-demo-02",
      category: "surf",
      subcategory: "Regatas",
      price: 99.9,
      stock: 15,
      colors: [{ name: "Petróleo", hex: "#0f5b5b" }],
      sizes: sizesApparel,
      description: "Regata leve de algodão orgânico, pensada para dias longos de praia.",
      composition: "100% algodão orgânico.",
      care: ["Lavar à máquina em água fria"],
      tags: ["surf", "praia"],
      relatedSlugs: ["boardshort-fluxo-wave", "camiseta-tide-surf"],
    },
    {
      sizeGuideRows: boneSizeGuide,
      slug: "bone-surf-classic",
      name: "Boné Surf Classic",
      brandSlug: "marca-demo-02",
      category: "surf",
      subcategory: "Acessórios",
      price: 79.9,
      stock: 22,
      colors: [{ name: "Areia", hex: "#d8cbb7" }],
      sizes: sizesAccessory,
      description: "Boné em sarja com aba desconstruída e fivela de metal para ajuste.",
      composition: "100% algodão.",
      care: ["Limpar com pano úmido"],
      tags: ["acessório", "praia"],
    },
    {
      sizeGuideRows: camisetaSizeGuide,
      slug: "camiseta-essential-city",
      name: "Camiseta Essential City",
      brandSlug: "marca-demo-03",
      category: "casual",
      subcategory: "Camisetas",
      price: 139.9,
      stock: 30,
      colors: [
        { name: "Preto", hex: "#111111" },
        { name: "Cinza claro", hex: "#e8e8e8" },
        { name: "Areia", hex: "#d8cbb7" },
      ],
      sizes: sizesApparel,
      description: "Camiseta de corte reto em algodão premium com caimento estruturado.",
      composition: "100% algodão pima.",
      care: ["Lavar à máquina em água fria", "Não usar alvejante"],
      isBestSeller: true,
      tags: ["casual", "básico"],
      relatedSlugs: ["calca-city-move", "bermuda-urban-fit"],
    },
    {
      sizeGuideRows: shortsSizeGuide,
      slug: "bermuda-urban-fit",
      name: "Bermuda Urban Fit",
      brandSlug: "marca-demo-03",
      category: "casual",
      subcategory: "Bermudas",
      price: 189.9,
      stock: 4,
      colors: [{ name: "Grafite", hex: "#666666" }, { name: "Preto", hex: "#111111" }],
      sizes: sizesApparel,
      description: "Bermuda de sarja com corte slim e acabamento premium.",
      composition: "98% algodão, 2% elastano.",
      care: ["Lavar à máquina em água fria", "Passar a ferro em temperatura média"],
      tags: ["casual"],
      relatedSlugs: ["camiseta-essential-city", "calca-city-move"],
    },
    {
      sizeGuideRows: calcaSizeGuide,
      slug: "calca-city-move",
      name: "Calça City Move",
      brandSlug: "marca-demo-03",
      category: "casual",
      subcategory: "Calças",
      price: 259.9,
      compareAtPrice: 299.9,
      stock: 9,
      colors: [{ name: "Preto", hex: "#111111" }],
      sizes: sizesApparel,
      description:
        "Calça de alfaiataria confortável com tecido de leve elasticidade, do escritório ao fim de tarde.",
      composition: "68% poliéster, 30% viscose, 2% elastano.",
      care: ["Lavar a seco recomendado", "Passar a ferro em temperatura baixa"],
      isNew: true,
      tags: ["casual", "trabalho"],
      relatedSlugs: ["camiseta-essential-city", "bermuda-urban-fit"],
    },
    {
      sizeGuideRows: boneSizeGuide,
      slug: "bone-city-basic",
      name: "Boné City Basic",
      brandSlug: "marca-demo-03",
      category: "casual",
      subcategory: "Acessórios",
      price: 69.9,
      stock: 50,
      colors: [{ name: "Preto", hex: "#111111" }, { name: "Cinza claro", hex: "#e8e8e8" }],
      sizes: sizesAccessory,
      description: "Boné minimalista em algodão com aba reta e logo bordado discreto.",
      composition: "100% algodão.",
      care: ["Limpar com pano úmido"],
      tags: ["acessório", "casual"],
    },
    {
      sizeGuideRows: camisetaSizeGuide,
      slug: "camiseta-hybrid-move",
      name: "Camiseta Hybrid Move",
      brandSlug: "marca-demo-04",
      category: "fitness",
      subcategory: "Camisetas",
      price: 159.9,
      stock: 0,
      colors: [{ name: "Preto", hex: "#111111" }, { name: "Petróleo", hex: "#0f5b5b" }],
      sizes: sizesApparel,
      description:
        "Camiseta híbrida que funciona tanto no treino quanto na rua, com toque suave e caimento reto.",
      composition: "60% algodão, 35% poliéster, 5% elastano.",
      care: ["Lavar à máquina em água fria"],
      isNew: true,
      tags: ["treino", "streetwear"],
      relatedSlugs: ["short-street-training", "jaqueta-corta-vento-fluxo"],
    },
    {
      sizeGuideRows: shortsSizeGuide,
      slug: "short-street-training",
      name: "Short Street Training",
      brandSlug: "marca-demo-04",
      category: "fitness",
      subcategory: "Shorts",
      price: 179.9,
      stock: 17,
      colors: [{ name: "Preto", hex: "#111111" }],
      sizes: sizesApparel,
      description: "Short de treino com estética streetwear e bolsos com zíper.",
      composition: "92% poliéster, 8% elastano.",
      care: ["Lavar à máquina em água fria"],
      tags: ["treino", "streetwear"],
      relatedSlugs: ["camiseta-hybrid-move", "jaqueta-corta-vento-fluxo"],
    },
    {
      sizeGuideRows: calcaSizeGuide,
      slug: "jaqueta-corta-vento-fluxo",
      name: "Jaqueta Corta-Vento Fluxo",
      brandSlug: "marca-demo-04",
      category: "casual",
      subcategory: "Calças",
      price: 299.9,
      stock: 2,
      colors: [{ name: "Preto", hex: "#111111" }, { name: "Grafite", hex: "#666666" }],
      sizes: sizesApparel,
      description: "Corta-vento leve e compactável, para dias de treino ao ar livre ou trajetos urbanos.",
      composition: "100% poliéster com tratamento repelente à água.",
      care: ["Lavar à máquina em água fria", "Não usar secadora"],
      isBestSeller: true,
      tags: ["streetwear", "treino", "viagem"],
      relatedSlugs: ["camiseta-hybrid-move", "short-street-training"],
    },
  ];
}
